<?php

namespace Behamin\BResources\Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Tests\CreatesApplication;

/**
 * Class TestCase
 *
 * @package Tests
 * @property \Illuminate\Foundation\Application $app
 */
abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected $resourcePath;

    /**
     * @var \Illuminate\Foundation\Application
     */
    protected $app;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->app = $this->createApplication();

        $this->resourcePath = base_path('app/Http/Resources/');
    }

    public function resourceFilePath($file){
        return $this->resourcePath . $file . '.php';
    }

}
